### ISSUE TITLE
Generate visual results

### ISSUE THREAD

**Issue by florian-hoenicke** [kwotsin/mimicry#10]
Hi, will it be possible to generate some images to make some visual checks of the network performances?

**Comment by kwotsin** [comment]
Hi @hoenickf, yes it's possible, there are several options:

1. You can visualise the tensorboard outputs using `tensorboard --logdir=/path/to/your/log`, and it should be under the image tab.

2. By default, when training, the generated images will be saved every 500 steps to the log directory at `/path/to/your/log/images`.

Hope it helps!
