### ISSUE TITLE
How to add a new module or net in this repo

### ISSUE THREAD

**Issue by Johnson-yue** [kwotsin/mimicry#11]
Hi, thank your sharing , and I want to add some net or module for testing ,like MSGAN architect， Eql Conv  ，and so on。 How should I do ?? 

I see you recommand pip install ， but I do not know if I add same new， what should I do or do nothing？？

**Comment by kwotsin** [comment]
Hi @Johnson-yue, I've included a detailed guide for implemented a new GAN from scratch, which is available here: https://mimicry.readthedocs.io/en/latest/guides/tutorial.html which you can refer to.

See also: https://github.com/kwotsin/mimicry/blob/master/examples/ssgan_tutorial.py for the full code

Hope it helps!
