### ISSUE TITLE
INFO: Propagated batch xxxx/1000  is very slow

### ISSUE THREAD

**Issue by Johnson-yue** [kwotsin/mimicry#12]
Hi， this progress is very slow and maybe it only using CPU for computiing！！！
（2~3 sec/batch）  can you update it for GPU using？

**Comment by kwotsin** [comment]
Hi @Johnson-yue, I believe simply installing the GPU version of TensorFlow should automatically use the GPU for the propagation. Perhaps you can try to use conda to install TensorFlow-GPU, e.g. `conda install tensorflow-gpu`

Hope it helps!

**Comment by Johnson-yue** [comment]
oh, this progress is depend on Tensorflow !! 
I got it
