### ISSUE TITLE
Did update code base without tensorflow ？？

### ISSUE THREAD

**Issue by Johnson-yue** [kwotsin/mimicry#14]
Hi， I see your code， including many tensorflow used ，such as 
`compute_fid`， `compute_kid`,  `compute_inception_score`, and so on 

Would you plan to update pytorch code for those function？？

**Comment by kwotsin** [comment]
Hi @Johnson-yue, indeed TensorFlow is used quite a bit for the metrics implementation, mainly to make sure the scores can be reproduced as closely to original as possible. For example as mentioned in https://github.com/kwotsin/mimicry/issues/7, inception score can be quite sensitive to weight differences when using a different model, and the tensorflow inception model most people use for research seems to be using a very particular implementation (e.g. the output node has >1k outputs).

However, indeed the tensorflow use seems to be quite bulky compared to a pure pytorch approach. Recently the move to TF2 also has some breaking changes that I'm hoping to update and wait to see if it these changes remain stable in the long run. Hopefully there won't be a need to update too much whenever TF updates!
