### ISSUE TITLE
Discriminator weights on SNGAN celeba 64x64

### ISSUE THREAD

**Issue by 07hyx06** [kwotsin/mimicry#19]
Thanks for your code!! I want to do some research on SNGAN, can you provide the discriminator weights of SNGAN on celeba 64x64 dataset? Thanks a lot!

**Comment by kwotsin** [comment]
No worries @07hyx06 -- here is the checkpoint for discriminator weights: https://drive.google.com/file/d/1Hf0xMUjlO9pMi3GynagsXo6q2cPCjomi/view?usp=sharing

Hope it helps!

_Note: current response/work is delayed due to COVID circumstances (no access to computing resources)._

**Comment by 07hyx06** [comment]
Thanks!!!
