### ISSUE TITLE
Incorrect read the docs documentation on training.Trainer

### ISSUE THREAD

**Issue by rvdmaazen** [kwotsin/mimicry#2]
The [read the docs webpage](https://mimicry.readthedocs.io/en/latest/modules/training.html#module-torch_mimicry.training.trainer) contains the wrong documentation for the `training.Trainer` class. Currently the documentation displayed is that of the `training.Logger` class.

**Comment by kwotsin** [comment]
Thanks for bringing this up! I have fixed the link now, feel free to let me know if you see any other errors!
