### ISSUE TITLE
Cannot import sagan when I use pip install. Please fix.

### ISSUE THREAD

**Issue by stephenllh** [kwotsin/mimicry#26]

**Comment by kwotsin** [comment]
Thanks for bringing this up! I have fixed the error -- I would be glad if you can let me know how SAGAN performs on your side. Currently it seems that SAGAN for low resolution CIFAR-10 performs worse than CGAN-PD, and for ImageNet, unfortunately will need 4 GPUs to reproduce it which I don't have access to.
