### ISSUE TITLE
The gap of FID on LSUN dataset.

### ISSUE THREAD

**Issue by cyq373** [kwotsin/mimicry#35]
On the LSUN dataset, the FID score of SNGAN is 25.87, while others are about 12. 
What do you think of this gap?

**Comment by kwotsin** [comment]
My best guess is across papers, there could be some inconsistency in producing FID based on the number of samples as FID exhibits strong bias with the number of samples: https://arxiv.org/pdf/1801.01401.pdf

This is why I would think it's crucial to reproduce the scores and explicitly indicate the number of samples used to compute the FID across papers.
