### ISSUE TITLE
Could you add the support for torch >= 1.8?

### ISSUE THREAD

**Issue by soroushsheikh** [kwotsin/mimicry#37]
I am trying to develop a GAN model and I found your library very useful (thanks btw). However, it seems that it's not compatible with the new versions of the torch. And that's a problem for me since many complex number tools are developed for the new version.
Thanks.

**Comment by kwotsin** [comment]
Thanks for reporting the issue. This should be resolved with https://github.com/kwotsin/mimicry/pull/38, and feel free to install the master version using:
```
pip install git+https://github.com/kwotsin/mimicry.git
```
