### ISSUE TITLE
Not an issue with the code, but the documentation

### ISSUE THREAD

**Issue by stephenllh** [kwotsin/mimicry#4]
"From the paper, for the exact training hyperparameters, the FID is reported to be 17.88 ± 0.64, whereas we achieved 17.77 ± 0.21 so our result is very close!"

Correct me if I am wrong, but isn't the FID the lower the better? So you actually beat the SOTA, I think. Great work by the way!

**Comment by kwotsin** [comment]
Hi @stephenllh, thanks for the comment! Indeed a lower FID is better, although in this case the difference is quite marginal and lower than the standard deviation. In practice, improvements are made at a much larger scale, e.g. in SSGAN their improvement over the baseline is around 2-3 points.
