### ISSUE TITLE
dtype bugs on windows10

### ISSUE THREAD

**Issue by rainbowtp** [kwotsin/mimicry#41]
windows10
python3.7
torch 1.7 
torchvision 0.8

# Error:
```
RuntimeError: Expected tensor for argument #1 'indices' to have scalar type Long; but got torch.cuda.IntTensor instead (while checking arguments for embedding)
```
# Solution
[code line](https://github.com/kwotsin/mimicry/blob/70ce919b0684b14af264881cc6acf4eccaff42b2/torch_mimicry/training/logger.py#L150)
```
def _get_fixed_labels(self, num_images, num_classes):
        """
        Produces fixed class labels for generating fixed images.
        """
        labels = np.array([i % num_classes for i in range(num_images)])
        labels = torch.from_numpy(labels).to(self.device)

        return labels
```
to
```
def _get_fixed_labels(self, num_images, num_classes):
        """
        Produces fixed class labels for generating fixed images.
        """
        labels = np.array([i % num_classes for i in range(num_images)]).astype('int64')
        labels = torch.from_numpy(labels).to(self.device)

        return labels
```
I don't know exactly why but it works well

**Comment by kwotsin** [comment]
@rainbowtp Thanks for testing out the version on Windows and providing a solution. I've not planned to build this lib on Windows, so this lib may not work. That said, I also updated the packages and froze the versions to prevent backwards compatibility issues when TF/Torch updates in the future. You can try reinstalling with `pip install git+https://github.com/kwotsin/mimicry.git` to see if it works
