### ISSUE TITLE
How to calculate the FID IS after the experiments? 

### ISSUE THREAD

**Issue by sumorday** [kwotsin/mimicry#43]
the Example outputs without the detail of Fid

I can only see this:
INFO: FID Evaluation completed!

**Comment by kwotsin** [comment]
@sumorday do you have a reproducible example to show? The example (modifying training step to be 2 for checking only) should give something like this:
```
INFO: Restoring checkpoint for D...
INFO: Restoring checkpoint for G...
INFO: Starting training from global step 2...
INFO: Saving final checkpoints...
INFO: Training Ended.
INFO: FID at step 2 has been computed. Skipping...
INFO: FID (step 2): 350.3838899477446 (± 7.089700685797075) 
INFO: FID Evaluation completed!
```
I think this could be related to the confusion in the README where the dataset arg is an unused version in the lib. I've updated the library since, so please feel free to reinstall with `pip install git+https://github.com/kwotsin/mimicry.git`

**Comment by sumorday** [comment]
INFO: Saving final checkpoints...
INFO: Training Ended.
INFO: Checkpoint at step 100 does not exist. Skipping...
INFO: FID Evaluation completed!
{}

I guess that's about checkpoints. If I only run 200 epoch, the Checkpoint at step 100 does not exist..

**Comment by sumorday** [comment]
Hi! kwotsin. 
I made a colab link 
https://colab.research.google.com/drive/1URvd2B59mZztu7bS1Y17P27nxVx0us6H#scrollTo=hxSfGV1Oj5cm
Just only epoch 200 times and record the FID each 100 steps.
I guess the FID result in the folder ./log 
there is a file name is fid_50k_50k.json
I am still not sure how to find the FID result. 
How to modify training step to be 2  or 100 or 200 for checking only?in which file?
How can I do... Thank you in advance

**Comment by sumorday** [comment]
Oh I found this file.
https://github.com/kwotsin/mimicry/blob/master/examples/sngan_example.py
This problem solved 
Dear kwotsin you should use this as an example. anyway. Thank you!!!
